window.PORTFOLIO_WIDGET_DATA = {
  portfolio: {
    title: "SOLIDWORKS Portfolio Horizons",
    description:
      "A tenant-ready widget prototype for browsing the SOLIDWORKS portfolio by horizon, drilling into roles, and understanding which apps are primary versus shared across the broader role landscape.",
    primaryAction: {
      label: "Open Portfolio Playbook",
      href: "https://example.com/portfolio-playbook",
      external: true,
    },
    secondaryAction: {
      label: "Open Source Database",
      href: "https://example.com/portfolio-database",
      external: true,
    },
    lastUpdated: "2026-04-14",
  },
  horizons: [
    {
      id: "h1",
      label: "Horizon 1",
      name: "Market-Ready",
      description: "Priority roles and offers with immediate customer value and current go-to-market focus.",
    },
    {
      id: "h2",
      label: "Horizon 2",
      name: "Growth & Expansion",
      description: "High-potential offers that deepen adoption and expand platform usage after the initial landing motion.",
    },
    {
      id: "h3",
      label: "Horizon 3",
      name: "Strategic Incubation",
      description: "Emerging roles and offers being evaluated for product-market fit and future strategic investment.",
    },
  ],
  roles: [
    {
      code: "X1G",
      name: "SOLIDWORKS PLM Standard",
      domain: "Governance",
      subDomain: "Develop & Release",
      horizon: "h1",
      summary: "A core Horizon 1 governance role focused on collaborative release, project planning, and specification workflows.",
    },
    {
      code: "X2G",
      name: "SOLIDWORKS PLM Professional",
      domain: "Governance",
      subDomain: "Develop & Release",
      horizon: "h1",
      summary: "Builds on PLM Standard with a broader operational footprint across release and planning activities.",
    },
    {
      code: "X0W",
      name: "SOLIDWORKS xDesign",
      domain: "Design",
      subDomain: "Cloud CAD",
      horizon: "h1",
      summary: "Entry-point cloud design role connecting modeling workflows to the broader platform foundation.",
    },
    {
      code: "X4W",
      name: "SOLIDWORKS Design Ultimate",
      domain: "Design",
      subDomain: "Mechanical",
      horizon: "h1",
      summary: "The broadest Horizon 1 design role, combining mechanical design with adjacent platform apps.",
    },
    {
      code: "X1N",
      name: "SOLIDWORKS Simulation Designer",
      domain: "Simulation",
      subDomain: "Structure",
      horizon: "h1",
      summary: "Entry simulation role for structural workflows tied closely to design iteration.",
    },
    {
      code: "XPP",
      name: "Project Planner",
      domain: "Plan",
      subDomain: "Execution",
      horizon: "h2",
      summary: "Planning and execution role used to expand value once the initial platform landing is established.",
    },
    {
      code: "XEN",
      name: "Product Release Engineer",
      domain: "Develop & Release",
      subDomain: "Release",
      horizon: "h2",
      summary: "Release-focused role that strengthens change, maturity, and downstream handoff processes.",
    },
    {
      code: "PAU",
      name: "3D Product Architect",
      domain: "Develop & Release",
      subDomain: "Product Definition",
      horizon: "h2",
      summary: "Supports product structure and release architecture beyond the initial core landing motion.",
    },
    {
      code: "ICE",
      name: "Immersive Collaboration Experience",
      domain: "Shape & Style",
      subDomain: "Immersive",
      horizon: "h3",
      summary: "Strategic incubation role exploring immersive review and collaboration experiences.",
    },
    {
      code: "VIZ",
      name: "Virtual Reality Reviewer",
      domain: "Shape & Style",
      subDomain: "Immersive",
      horizon: "h3",
      summary: "Emerging VR review role positioned as a future-facing complement to broader collaboration flows.",
    },
  ],
  apps: [
    { id: "collaborative-tasks", name: "Collaborative Tasks" },
    { id: "engineering-release", name: "Engineering Release" },
    { id: "project-planning", name: "Project Planning" },
    { id: "specification-management", name: "Specification Management" },
    { id: "3dlearn", name: "3DLearn" },
    { id: "cad-data-processor-monitoring", name: "CAD Data Processor Monitoring" },
    { id: "collaboration-package-management", name: "Collaboration Package Management" },
    { id: "kanban-board", name: "Kanban Board" },
    { id: "project-planning-control-center", name: "Project Planning Control Center" },
    { id: "scientific-settings-and-administration", name: "Scientific Settings and Administration" },
    { id: "specification-administration", name: "Specification Administration" },
    { id: "welcome", name: "Welcome" },
  ],
  roleApps: [
    { roleCode: "X1G", appId: "collaborative-tasks", primary: true, sharedWith: ["CSV", "X4W", "X2G"] },
    { roleCode: "X1G", appId: "engineering-release", primary: true, sharedWith: ["X4W", "X2G", "X3G"] },
    { roleCode: "X1G", appId: "project-planning", primary: true, sharedWith: ["X4W", "X2G", "X3G"] },
    { roleCode: "X1G", appId: "specification-management", primary: true, sharedWith: ["X2G", "X3G", "XSR"] },
    { roleCode: "X1G", appId: "3dlearn", primary: false, sharedWith: ["X1W", "X2W", "X3W", "X4W"] },
    { roleCode: "X1G", appId: "cad-data-processor-monitoring", primary: false, sharedWith: ["X0W", "X1W", "X2W", "X3W"] },
    { roleCode: "X1G", appId: "collaboration-package-management", primary: false, sharedWith: ["X4W", "X2G", "X3G"] },
    { roleCode: "X1G", appId: "kanban-board", primary: false, sharedWith: ["CSV", "X4W", "X2G"] },
    { roleCode: "X1G", appId: "project-planning-control-center", primary: false, sharedWith: ["X4W", "X2G", "X3G"] },
    {
      roleCode: "X1G",
      appId: "scientific-settings-and-administration",
      primary: false,
      sharedWith: ["X2G", "X3G", "XSR"],
    },
    { roleCode: "X1G", appId: "specification-administration", primary: false, sharedWith: ["X2G", "X3G", "XSR"] },
    { roleCode: "X1G", appId: "welcome", primary: false, sharedWith: ["X1W", "X2W", "X3W", "X4W"] },
    { roleCode: "X2G", appId: "collaborative-tasks", primary: true, sharedWith: ["CSV", "X4W", "X1G"] },
    { roleCode: "X2G", appId: "engineering-release", primary: true, sharedWith: ["X4W", "X1G", "X3G"] },
    { roleCode: "X2G", appId: "project-planning", primary: true, sharedWith: ["X4W", "X1G", "X3G"] },
    { roleCode: "X2G", appId: "specification-management", primary: true, sharedWith: ["X1G", "X3G", "XSR"] },
    { roleCode: "X4W", appId: "collaborative-tasks", primary: false, sharedWith: ["CSV", "X1G", "X2G"] },
    { roleCode: "X4W", appId: "engineering-release", primary: false, sharedWith: ["X1G", "X2G", "X3G"] },
    { roleCode: "X4W", appId: "project-planning", primary: false, sharedWith: ["X1G", "X2G", "X3G"] },
    { roleCode: "XPP", appId: "project-planning", primary: true, sharedWith: ["X1G", "X2G", "X3G"] },
    { roleCode: "XPP", appId: "kanban-board", primary: true, sharedWith: ["CSV", "X1G", "X2G"] },
    { roleCode: "XEN", appId: "engineering-release", primary: true, sharedWith: ["X1G", "X2G", "X3G"] },
  ],
};
